/* V8 unified analysis. All enriched figures, market data and workflow instances are DEMO fixtures. */
(function(root,f){if(typeof module==='object'&&module.exports)module.exports=f(require('./core.js'));else root.HMAnalytics=f(root.HMPilot);})(typeof globalThis!=='undefined'?globalThis:this,function(C){'use strict';
const dims=['面料','版型','功能','风格','袖长/长度'];
const sum=(xs,k)=>xs.reduce((v,x)=>v+(Number.isFinite(x[k])?x[k]:0),0);
const ratio=(a,b)=>Number.isFinite(a)&&Number.isFinite(b)&&b>0?a/b:null;
function enrich(input,assets){const s=C.clone(input);s.edition='v8';const templates=assets.productTemplates;
 for(const p of templates){if(s.products.some(x=>x.id===p.id))continue;const i=templates.indexOf(p);s.products.push({id:p.id,name:p.name,platform:p.platform,shop:p.shop,concept:p.concept,category:p.category,unit:p.unit,listed:C.addDays('2026-09-22',-(i%5===0?10+i%19:40+i)),article:'V8-DEMO-'+i,seasonal:p.season||'待核验',stock:300+(i*137)%2900,pool:'POOL-EX-'+i,archived:false,stageLabel:'阶段输出待接入',sourceState:'success',slice:i%4===0?'2026-09-19':null,imageRecord:i%3===0,sabRecord:i%4===0,adState:i%5===0?'暂停':i%2?'在推记录':'未匹配',thumbnailType:i%4,demo:true});}
 for(let i=0;i<s.products.length;i++){const p=s.products[i],t=templates.find(x=>x.id===p.id)||{};p.shop=p.platform==='天猫'?'H&M 天猫演示店':'H&M 京东演示店';p.l1=t.l1||'上装';p.tags=C.clone(t.tags||{});p.s4=!!t.s4;p.leadDays=t.leadDays||7;p.attributeSource='V6命名/分类模板；V8属性仅演示，非已核验真实成分';p.stockAt='2026-09-21T23:00:00+08:00';p.priceAt='2026-09-21';p.pageState=i%4===0?'待核验':'来源有透出记录';
  if(!s.daily.some(x=>x.productId===p.id)){for(let d='2026-08-18';d<='2026-10-08';d=C.addDays(d,1)){if(d<p.listed)continue;const n=C.dayDiff('2026-08-18',d),uv=Math.round((180+i*37)*(1+.1*Math.sin((n+i)/3))),buyers=Math.round(uv*(.012+(i%12)*.002));s.daily.push({productId:p.id,date:d,uv,buyers,gmv:Math.round(buyers*1.12*p.unit),ready:true});}}
  for(const r of s.daily.filter(x=>x.productId===p.id)){r.qty=Math.max(r.buyers,Math.round(r.buyers*1.14));r.refund=Math.round(r.gmv*(.035+(i%7)*.012));r.fav=i%11===0?null:Math.round(r.uv*(.01+i%5*.005));r.cart=i%11===0?null:Math.round(r.uv*(.03+i%6*.008));r.spend=p.adState==='在推记录'?Math.round(r.gmv*(.12+i%4*.03)):p.adState==='暂停'?0:null;}
 }
 s.skus=[];for(let i=0;i<s.products.length;i++){const p=s.products[i],colors=['黑色','米白'],sizes=['S','M','L','XL'];let weights=[];for(let j=0;j<8;j++)weights.push((i%7===3&&[1,2].includes(j))?0:1+((i+j)%3));const total=weights.reduce((a,b)=>a+b,0);let allocated=0;for(let j=0;j<8;j++){let n=j===7?p.stock-allocated:Math.floor(p.stock*weights[j]/total);allocated+=n;s.skus.push({id:p.id+'-SKU-'+j,productId:p.id,color:colors[Math.floor(j/4)],size:sizes[j%4],core:[1,2].includes(j%4),stock:n,pool:p.pool,at:p.stockAt});}}
 s.market=makeMarket(s);s.flows=makeFlows(s);return s;
}
function makeMarket(s){const cats=['毛针织衫','T恤','衬衫','牛仔裤','连衣裙','短外套'];const periods={current:{label:'本期 · 09.15—09.21',start:'2026-09-15',end:'2026-09-21'},previous:{label:'对比期 · 09.08—09.14',start:'2026-09-08',end:'2026-09-14'}};const m={demo:true,scope:'天猫 · 同类目商品/商家榜（演示）',rankMetric:'商家成交排名（演示字段）',periods,categories:[],merchants:[],items:[],benefits:[]};
 cats.forEach((cat,i)=>{const own={id:'hm',name:'H&M 演示店',current:[12,112,26,18,35,22][i],previous:[9,89,29,15,31,24][i]};m.categories.push({name:cat,own,comparable:true,source:'DEMO-RANK-'+(i+1),readAt:'2026-09-22 10:30',expectedLimit:300});
 const merchants=[own,{id:'m'+i+'a',name:'竞争商家 A'+(i+1)+'（演示）',current:own.current-3,previous:own.previous+7},{id:'m'+i+'b',name:'竞争商家 B'+(i+1)+'（演示）',current:own.current-5,previous:Math.max(1,own.previous-4)},{id:'m'+i+'c',name:'竞争商家 C'+(i+1)+'（演示）',current:own.current-1,previous:null},{id:'m'+i+'d',name:'竞争商家 D'+(i+1)+'（演示）',current:own.current-2,previous:own.previous+12}];
 for(const x of merchants)m.merchants.push({...x,category:cat});
 const matches=s.products.filter(p=>p.platform==='天猫'&&p.category===cat),fabric=i===0?['羊毛混纺','针织','棉']:i===3?['棉','牛仔']:['棉','亚麻/麻','针织'];
 for(let j=0;j<18;j++){const merch=merchants[j%4],p=merch.id==='hm'?matches[(Math.floor(j/4))%Math.max(1,matches.length)]:null;const tags={'面料':j%6===5?[]:[fabric[j%fabric.length]],'版型':[j%3===0?'修身':j%3===1?'宽松':'直筒'],'功能':j%3===0?['透气']:j%4===0?['免烫/抗皱']:[],'风格':[j%2?'商务/通勤':'休闲'],'袖长/长度':[j%2?'长袖':'短袖']};if(p&&m.items.some(x=>x.category===cat&&x.productId===p.id))continue;m.items.push({id:'MKT-'+i+'-'+j,category:cat,merchantId:merch.id,merchantName:merch.name,period:'current',rank:j*13+3,previousRank:j%5===0?null:j*13+8,name:p?p.name:cat+' · '+(tags['面料'][0]||'未标注面料')+' '+tags['版型'][0]+'款（演示）',tags,titleOnly:true,productId:p?.id||'',buyersRange:j%2?'100—250':'250—500',uvRange:'2,500—5,000',price:null,source:'DEMO-TOP300-'+i,observedAt:'2026-09-21'});}
 for(const x of merchants){const state=x.id==='hm'?'missing':x.id.endsWith('a')?'observed':x.id.endsWith('b')?'expired':'missing';m.benefits.push({id:'BEN-'+i+'-'+x.id,category:cat,merchantId:x.id,state,offer:state==='missing'?null:x.id.endsWith('a')?'满299减30（示例采集）':'会员专享券（历史示例）',conditions:state==='missing'?'未取得可核验权益资料':'指定商品及指定人群；是否与其他权益叠加未核验',validStart:state==='expired'?'2026-09-01':'2026-09-15',validEnd:state==='expired'?'2026-09-07':'2026-09-21',capturedAt:'2026-09-20 11:00',evidence:'DEMO-EVIDENCE-'+i+'-'+x.id,limitation:'仅为交互演示，不是真实商家权益，不用于解释反超因果。'});}
 });return m;}
function makeFlows(s){const node=(id,title,extra={})=>({id,title,kind:'human',state:'waiting',dependencies:[],...extra});return [
 {id:'FLOW-DAILY',title:'新品日常运营 · 09月22日批次',scene:'日常',owner:'lead',source:'已有阶段清单 → 模拟流程实例；真实触发未接入',version:1,due:'2026-09-23',goal:'让新品来源、人员执行和核验正确交接',nodes:[node('D0','数据到齐与源校验',{kind:'system',state:'done',output:'新品源快照 DEMO-SOURCE-v1'}),node('D1','阶段清单与AI核查包',{kind:'ai',state:'done',dependencies:['D0'],output:'AI / 输入产物 v1（演示）'}),node('D2','视频状态核查与执行',{taskId:'TASK-001',dependencies:['D1']}),node('D3','人工提交独立核验',{taskId:'TASK-006',dependencies:['D1']}),node('D4','推广来源异常修复',{taskId:'TASK-007',dependencies:['D0']}),node('D5','历史新品后续核查',{taskId:'TASK-008',dependencies:['D0']})]},
 {id:'FLOW-CAMPAIGN',title:'秋季主题周 · 活动推进',scene:'活动',owner:'lead',source:'飞书SOP自动触发方向 · 下方运行状态为演示',version:3,due:'2026-09-25',goal:'已批准目标与价盘驱动页面、推广并行筹备和联合QA',nodes:[node('A01','活动立项与统筹',{kind:'human',state:'done',owner:'lead',output:'活动Brief v1'}),node('A02','目标与流量预测',{kind:'ai',state:'done',dependencies:['A01'],output:'预测草稿 v2 / 已核对（演示）'}),node('A03','商品-RD-权益-价盘',{kind:'human',state:'done',owner:'merch',dependencies:['A02'],output:'价盘 v3（示例批准版）'}),node('A04','页面与视觉生产',{taskId:'TASK-002',dependencies:['A03']}),node('A05','渠道报名材料整理',{kind:'ai',state:'running',dependencies:['A03'],owner:'ops',runId:'DEMO-RUN-103',elapsed:'运行 18 分钟（演示）'}),node('A06','后台配置',{state:'waiting',dependencies:['A03','A05'],owner:'ops'}),node('A07','活动QA与上线',{taskId:'TASK-010',dependencies:['A04','A06']}),node('A08','会员活动',{state:'not_applicable',reason:'本演示活动无会员分支；仅为样本配置'}),node('A10','经营监控与复盘',{state:'waiting',dependencies:['A07'],owner:'lead'})]},
 {id:'FLOW-STRATEGY',title:'年度品类目标拆解 · 专项',scene:'专项',owner:'merch',source:'策略=专项；年度计划示例，非临时商品实验',version:1,due:'2026-09-30',goal:'完成年度目标、品类拆解、资源讨论及批准版本',nodes:[node('P01','品牌目标输入',{kind:'human',state:'done',owner:'lead',output:'品牌目标（演示摘要）'}),node('P02','年度结构分析与草稿',{kind:'ai',state:'done',dependencies:['P01'],output:'年度品类方案草稿 v1'}),node('P03','商品经理核对',{taskId:'TASK-011',dependencies:['P02']}),node('P04','管理者复核与发布',{state:'waiting',dependencies:['P03'],owner:'lead'})]}
 ];}
function metrics(s,p,start,end){if(!C.validDate(start)||!C.validDate(end)||start>end)return {gmv:null,uv:null,cr:null,missing:['日期范围无效'],observedDays:0};const effectiveStart=p.listed>start?p.listed:start;const partialAge=p.listed>start;if(effectiveStart>end)return {gmv:null,uv:null,cr:null,missing:[],observedDays:0,partialAge:true,notListed:true};const dates=C.datesBetween(effectiveStart,end),rs=[];const missing=[];for(const d of dates){const found=s.daily.filter(x=>x.productId===p.id&&x.date===d);if(d>s.completeThrough||found.length!==1||!found[0].ready||!['uv','buyers','gmv'].every(k=>Number.isFinite(found[0][k]))){missing.push(d);}else rs.push(found[0]);}
 const base={missing,partialAge,observedDays:rs.length,windowDays:C.dayDiff(start,end)+1,coverage:ratio(rs.length,dates.length)};if(missing.length)return {...base,gmv:null,uv:null,buyers:null,cr:null,qty:null,refund:null,fav:null,cart:null,spend:null,net:null,refundRate:null};
 const optional=k=>rs.every(r=>Number.isFinite(r[k]))?sum(rs,k):null;const uv=sum(rs,'uv'),buyers=sum(rs,'buyers'),gmv=sum(rs,'gmv'),qty=optional('qty'),refund=optional('refund');return {...base,uv,buyers,gmv,cr:ratio(buyers,uv),qty,refund,net:refund===null?null:gmv-refund,refundRate:ratio(refund,gmv),asp:ratio(gmv,qty),fav:optional('fav'),cart:optional('cart'),favRate:ratio(optional('fav'),uv),cartRate:ratio(optional('cart'),uv),spend:optional('spend')};}
function productRows(s,f={},start,end){const pool=s.products.filter(p=>(!f.platform||p.platform===f.platform)&&(!f.concept||p.concept===f.concept)&&(!f.category||p.category===f.category));const all=pool.map(p=>{const now=metrics(s,p,start,end),n=C.dayDiff(start,end)+1,before=metrics(s,p,C.addDays(start,-n),C.addDays(start,-1));const sk=s.skus.filter(x=>x.productId===p.id),core=sk.filter(x=>x.core),known=sk.length>0;const demand=now.qty!==null&&now.observedDays?now.qty/now.observedDays:null;return {...now,id:p.id,product:p,category:p.category,isNew:C.inNewList(p,s.clock),before,mom:!now.partialAge&&!before.partialAge&&now.gmv!==null&&before.gmv>0?now.gmv/before.gmv-1:null,sizeRate:known?core.filter(x=>x.stock>0).length/core.length:null,coreMissing:known?core.filter(x=>x.stock===0).length:null,cover:demand>0?p.stock/demand:null,taskCount:s.tasks.filter(t=>t.productId===p.id&&!C.CLOSED.has(t.status)).length,policy:C.currentPolicy(s,p.id),rank:null};});
 const groups=new Map();for(const r of all){const k=r.product.platform+'|'+r.product.shop;if(!groups.has(k))groups.set(k,[]);groups.get(k).push(r);}for(const rows of groups.values()){rows.filter(r=>r.gmv!==null&&r.gmv>0).sort((a,b)=>b.gmv-a.gmv||a.id.localeCompare(b.id)).forEach((r,i)=>r.rank=i+1);}
 const out=all.filter(r=>{const p=r.product;if(f.newOnly&&!r.isNew)return false;if(f.top){if(f.top==='no-sales'){if(r.gmv!==0)return false;}else{const [a,b]=f.top.split('-').map(Number);if(!r.rank||r.rank<a||r.rank>b)return false;}}if(f.search&&![p.name,p.id,p.article].some(x=>x.toLowerCase().includes(String(f.search).toLowerCase())))return false;if(f.source&&p.sourceState!==f.source)return false;if(f.stage&&p.stageLabel!==f.stage)return false;if(f.ad&&p.adState!==f.ad)return false;if(f.s4&&!p.s4)return false;if(f.activity&&!s.tasks.some(t=>t.productId===p.id&&t.activity===f.activity))return false;if(f.taskStatus&&!s.tasks.some(t=>t.productId===p.id&&t.status===f.taskStatus))return false;if(f.segment==='active'&&!(r.gmv>0))return false;if(f.segment==='growth'&&!(r.mom>0))return false;if(f.segment==='new-sales'&&!(r.gmv>0&&r.before.gmv===0))return false;if(f.segment==='paid'&&p.adState!=='在推记录')return false;if(f.segment==='s4'&&!p.s4)return false;if(f.tag&&!((p.tags[f.dimension]||[]).includes(f.tag)||(f.tag==='未标注'&&!(p.tags[f.dimension]||[]).length)))return false;if(f.price&&priceBand(r.asp)!==f.price)return false;if(f.candidateIds&&!f.candidateIds.includes(p.id))return false;return true;});
 return out.sort((a,b)=>f.sort==='uv'?(b.uv??-1)-(a.uv??-1):f.sort==='new'?b.product.listed.localeCompare(a.product.listed):(b.gmv??-1)-(a.gmv??-1));}
function priceBand(asp){if(!Number.isFinite(asp))return '暂无成交价';return asp<50?'0-49':asp<100?'50-99':asp<200?'100-199':asp<300?'200-299':asp<500?'300-499':'500+';}
function groups(rows,key,dimension){const map=new Map();for(const r of rows){let ks=key==='tag'?(r.product.tags[dimension]?.length?r.product.tags[dimension]:['未标注']):[key==='price'?priceBand(r.asp):key==='top'?(!r.rank?'无销量/不可排名':r.rank<=10?'1-10':r.rank<=20?'11-20':'21-50'):r.category];for(const k of ks){if(!map.has(k))map.set(k,{key:k,rows:[],gmv:0,qty:0,uv:0,buyers:0,valid:0,active:0,count:0});const x=map.get(k);x.rows.push(r);x.count++;if(r.gmv!==null){x.valid++;x.gmv+=r.gmv;x.qty+=r.qty??0;x.uv+=r.uv;x.buyers+=r.buyers;if(r.gmv>0)x.active++;}}}const total=rows.reduce((v,x)=>v+(x.gmv??0),0);return [...map.values()].map(x=>({...x,share:ratio(x.gmv,total),cr:ratio(x.buyers,x.uv),asp:ratio(x.gmv,x.qty),activeRate:ratio(x.active,x.valid)})).sort((a,b)=>b.gmv-a.gmv);}
function rankState(r,own,comparable=true){if(!comparable||![r.current,r.previous,own.current,own.previous].every(Number.isFinite))return 'unknown';if(r.current===own.current)return 'tie';if(r.current<own.current)return r.previous>=own.previous?'overtake':'leading';return 'behind';}
function industrySummary(s,category,merchantId=''){const items=s.market.items.filter(x=>x.category===category&&x.period==='current'&&(!merchantId||x.merchantId===merchantId));const unique=[...new Map(items.map(x=>[x.id,x])).values()],features={};for(const dim of dims){const counts=new Map();for(const item of unique){for(const tag of new Set(item.tags[dim]?.length?item.tags[dim]:['未标注']))counts.set(tag,(counts.get(tag)||0)+1);}features[dim]=[...counts].map(([tag,count])=>({tag,count,share:ratio(count,unique.length)})).sort((a,b)=>b.count-a.count);}return {items:unique,sampleSize:unique.length,features};}
function candidates(s,{category,dimension,tag}){return s.products.filter(p=>p.platform==='天猫'&&p.category===category&&(!tag||(p.tags[dimension]||[]).includes(tag)));}
function nodeState(s,n,flow){if(n.taskId){const t=s.tasks.find(x=>x.id===n.taskId);if(!t)return {state:'unknown',owner:'',executor:'未知',task:null};if(flow&&t.status==='queued'&&n.dependencies?.some(id=>{const dep=flow.nodes.find(x=>x.id===id);return dep&&!['done','not_applicable','waived'].includes(nodeState(s,dep).state);})){return {state:'waiting',owner:t.owner,executor:'人员',task:t,reason:'等待上游节点'};}return {state:t.status,owner:t.status==='review'?t.verifier:t.owner,executor:'人员',task:t,late:!C.CLOSED.has(t.status)&&t.due<s.clock};}return {state:n.state||'unknown',owner:n.owner||'',executor:n.kind==='ai'?'AI':n.kind==='system'?'系统':'人员',late:false};}
function validate(s){C.validateBackup(s);if(s.edition!=='v8'||!Array.isArray(s.skus)||!Array.isArray(s.flows)||!s.market||!Array.isArray(s.market.categories)||!Array.isArray(s.market.items)||!Array.isArray(s.market.merchants)||!Array.isArray(s.market.benefits))throw Error('仅支持完整V8演示备份，版本或分析字段缺失');for(const p of s.products)if(!p.tags||!p.platform||!p.shop)throw Error('商品分析字段不完整');if(s.skus.some(x=>!s.products.some(p=>p.id===x.productId)||!Number.isFinite(x.stock)||x.stock<0))throw Error('SKU映射或数量无效');return C.clone(s);}
return {enrich,metrics,productRows,groups,priceBand,rankState,industrySummary,candidates,nodeState,validate,dims,ratio};
});
