/* HM V7: deterministic, side-effect-free demo domain layer. Not server authorization. */
(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.HMPilot=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){'use strict';
const CLOSED=new Set(['done','waived','cancelled']);
const clone=x=>JSON.parse(JSON.stringify(x));
const error=(message,code='VALIDATION')=>{const e=new Error(message);e.code=code;throw e;};
const finite=x=>typeof x==='number'&&Number.isFinite(x);
function validDate(s){if(typeof s!=='string'||!/^\d{4}-\d{2}-\d{2}$/.test(s))return false;const d=new Date(s+'T00:00:00Z');return !Number.isNaN(d.getTime())&&d.toISOString().slice(0,10)===s;}
function addDays(s,n){if(!validDate(s))error('日期无效');const d=new Date(s+'T00:00:00Z');d.setUTCDate(d.getUTCDate()+n);return d.toISOString().slice(0,10);}
function dayDiff(a,b){return Math.round((new Date(b+'T00:00:00Z')-new Date(a+'T00:00:00Z'))/86400000);}
function shanghaiDay(s){const d=new Date(s);if(!Number.isFinite(d.getTime()))error('生效时间无效');return new Date(d.getTime()+8*3600000).toISOString().slice(0,10);}
function inNewList(p,T){return validDate(p.listed)&&p.listed>=addDays(T,-29)&&p.listed<=T;}
function isManager(s,id){return ['manager','merch'].includes(s.users.find(x=>x.id===id)?.role);}
function currentPolicy(s,pid){return s.policies.filter(x=>x.productId===pid&&x.active).sort((a,b)=>(b.version||0)-(a.version||0))[0]||null;}
function activeAction(t){return !['cancelled','waived','blocked'].includes(t.status)&&(!CLOSED.has(t.status)||t.plan?.enabled);}
function actionInterval(t){const start=t.effectiveAt?shanghaiDay(t.effectiveAt):t.plannedStart;return [start,t.effectiveAt?addDays(start,Math.max(...(t.plan?.milestones||[0]))):(t.observationEnd||t.plannedEnd||start)];}
function overlaps(a,b){const [as,ae]=actionInterval(a),[bs,be]=actionInterval(b);return !!as&&!!bs&&as<=be&&bs<=ae;}
function conflicts(s,t){const out=[];const pol=currentPolicy(s,t.productId);if(t.kind==='purchase'&&pol?.mode==='stop_purchase')out.push({level:'hard',type:'policy',id:pol.id,title:'当前策略：停止新增采购',detail:pol.reason,version:pol.version});
 const p=s.products.find(p=>p.id===t.productId);for(const a of s.tasks){if(a.id===t.id||!activeAction(a)||!overlaps(a,t))continue;const same=t.productId&&a.productId===t.productId;const pa=s.products.find(p=>p.id===a.productId);const pool=p&&pa&&p.pool&&p.pool===pa.pool;
  if(!same&&!pool)continue;
  const factual=['data_check','video_check','report','manual','page_check'];if(factual.includes(t.kind)||factual.includes(a.kind))continue;
  if(same&&t.resource===a.resource&&['main_image','video','price'].includes(t.kind)&&!CLOSED.has(a.status))out.push({level:'hard',type:'overwrite',id:a.id,title:'同一位置的修改重叠',detail:a.title,version:a.version});
  else if(same)out.push({level:'soft',type:'attribution',id:a.id,title:'同期动作影响效果解释',detail:a.title,version:a.version});
  else if(pool&&['ad_budget','purchase','allocation'].includes(t.kind)&&['ad_budget','purchase','allocation'].includes(a.kind))out.push({level:'soft',type:'inventory_pool',id:a.id,title:'共享库存池需要协调',detail:a.title,version:a.version});
 }
 return out;
}
function conflictSignature(c){return c.map(x=>[x.type,x.id,x.version]).sort().map(x=>x.join(':')).join('|');}
function blocking(s,t){const cs=conflicts(s,t);if(cs.some(x=>x.level==='hard'))return cs.find(x=>x.level==='hard').type==='policy'?'当前停止采购策略限制本动作，请先由经理复核。':'存在同一目标的直接冲突，请先错开安排或取消重复动作。';if(cs.length&&t.coordination?.signature!==conflictSignature(cs))return '存在跨端口同期动作，需要主管确认协调方式。';return '';}
function datesBetween(a,b){let o=[];for(let d=a;d<=b;d=addDays(d,1)){o.push(d);if(o.length>366)error('观察窗口过长');}return o;}
function aggregateWindow(s,pid,dates,metric){const rows=dates.map(d=>s.daily.filter(r=>r.productId===pid&&r.date===d));const missing=dates.filter((d,i)=>rows[i].length!==1||!rows[i][0].ready||!finite(rows[i][0].uv)||!finite(rows[i][0].buyers)||!finite(rows[i][0].gmv));if(missing.length)return {data:null,missing};const r=rows.map(x=>x[0]);const uv=r.reduce((n,x)=>n+x.uv,0),buyers=r.reduce((n,x)=>n+x.buyers,0),gmv=r.reduce((n,x)=>n+x.gmv,0);return {data:{uv,buyers,gmv,value:metric==='gmv'?gmv/dates.length:(uv>0?buyers/uv:null),days:dates.length},missing:[]};}
function evaluate(s,t,milestone){const plan=t.plan||{};const base={taskId:t.id,planVersion:plan.version||1,milestone,metric:plan.metric||'cr',dataVersion:s.dataVersion,before:null,after:null,confounds:[],missing:[],limitation:'演示样本；描述前后变化，不证明动作带来因果提升。'};
 if(!plan.enabled)return {...base,status:'not_applicable',message:'本任务不需要经营效果评估'};
 if(t.status!=='done'||!t.effectiveAt)return {...base,status:'not_effective',message:'等待执行核验；提交并不代表生效'};
 const d=shanghaiDay(t.effectiveAt),bStart=addDays(d,-plan.baselineDays),bEnd=addDays(d,-1),aStart=addDays(d,1),aEnd=addDays(d,milestone);
 const ranges={beforeStart:bStart,beforeEnd:bEnd,afterStart:aStart,afterEnd:aEnd};
 if(s.completeThrough<aEnd)return {...base,...ranges,status:'waiting',message:`观察窗截至 ${aEnd}；完整数据仅到 ${s.completeThrough}`};
 const p=s.products.find(x=>x.id===t.productId);if(!p||p.listed>bStart)return {...base,...ranges,status:'insufficient',message:'商品上架后没有足够优化前基准，不把上架前缺失视为零'};
 const before=aggregateWindow(s,t.productId,datesBetween(bStart,bEnd),plan.metric),after=aggregateWindow(s,t.productId,datesBetween(aStart,aEnd),plan.metric);
 if(!before.data||!after.data)return {...base,...ranges,status:'insufficient',missing:[...before.missing,...after.missing],message:'观察窗口存在缺日或无效字段；未补零、未替换日期'};
 if(before.data.uv<plan.minUV||after.data.uv<plan.minUV||before.data.value===null||after.data.value===null)return {...base,...ranges,status:'insufficient',before:before.data,after:after.data,message:'样本不足，暂不判定变化'};
 const confounds=s.tasks.filter(a=>a.id!==t.id&&a.productId===t.productId&&a.effectiveAt&&a.status==='done'&&!['video_check','data_check','report','manual','page_check'].includes(a.kind)&&shanghaiDay(a.effectiveAt)>=bStart&&shanghaiDay(a.effectiveAt)<=aEnd).map(a=>({id:a.id,title:a.title,effectiveAt:a.effectiveAt}));
 return {...base,...ranges,status:'ready',before:before.data,after:after.data,delta:after.data.value-before.data.value,relative:before.data.value?after.data.value/before.data.value-1:null,confounds,message:confounds.length?'同期存在其他已生效动作，仅作组合变化观察':'可查看描述性前后变化；尚不证明因果'};
}
function bump(t){t.version=(t.version||0)+1;}
function addEvent(s,actor,action,id,detail){const event={id:'EV-'+(s.events.length+1).toString().padStart(5,'0'),at:new Date().toISOString(),businessDate:s.clock,actor,action,objectId:id,detail};s.events.unshift(event);return event;}
function enqueue(s,task,type,extra=''){const key=[task.id,type,task.version,extra].join('|');if(!s.notifications.some(n=>n.key===key))s.notifications.unshift({id:'N-'+(s.notifications.length+1),key,taskId:task.id,type,recipient:type==='待核验'?task.verifier:task.owner,status:'pending',createdAt:new Date().toISOString(),demo:true});}
function validatePlan(p){if(!p||typeof p.enabled!=='boolean')error('跟踪配置格式无效');if(!p.enabled)return;
 if(!['cr','gmv'].includes(p.metric)||!Number.isInteger(p.baselineDays)||p.baselineDays<1||p.baselineDays>30||!Array.isArray(p.milestones)||!p.milestones.length||p.milestones.length>4||p.milestones.some(n=>!Number.isInteger(n)||n<1||n>30)||!finite(p.minUV)||p.minUV<1||p.minUV>1000000)error('跟踪配置需要有效指标、1–30天窗口和样本门槛');
 if(new Set(p.milestones).size!==p.milestones.length)error('报告节点不能重复');
}
function cleanText(s,len=2000){return String(s??'').trim().slice(0,len);}
function applyCommand(input,actor,command){if(!command||!command.requestId)error('缺少请求标识');const fingerprint=JSON.stringify({actor,...command});const recorded=input.requests?.[command.requestId];if(recorded){if(recorded!==fingerprint)error('重复请求标识的内容不同');return clone(input);}
 const s=clone(input);s.requests=s.requests||{};const u=s.users.find(x=>x.id===actor);if(!u)error('无效身份／权限');const p=command.payload||{};let t=s.tasks.find(x=>x.id===command.id);const managerial=['manager','merch'].includes(u.role),lead=u.role==='manager';
 if(['policy','create','evaluateAll','sync','dataAdvance','macToggle','syncFailToggle','refresh'].includes(command.type)){}else{if(!t)error('未找到任务');if(command.version!==t.version)error('记录版本已经变化，请重新打开后确认','CONFLICT');}
 const owner=()=>{if(t.owner!==actor)error('你没有处理此任务的权限');};
 let detail='';switch(command.type){
 case 'start': owner();if(!['queued','blocked'].includes(t.status))error('当前状态不能开始');{const why=blocking(s,t);if(why)error(why);}t.status='running';t.blockedReason='';bump(t);detail='开始处理；未调用真实平台';break;
 case 'block':owner();if(CLOSED.has(t.status)||t.status==='review')error('当前状态不能标记阻塞');if(!cleanText(p.reason))error('请填写阻塞原因');t.status='blocked';t.blockedReason=cleanText(p.reason);bump(t);detail=t.blockedReason;break;
 case 'submit':owner();if(!['queued','running','blocked'].includes(t.status))error('当前任务不能重复提交');if(p.artifactVersion!==t.artifactVersion)error('产物版本已经改变，请核对新版');if(!cleanText(p.note)||!cleanText(p.evidence)||!p.effectiveAt)error('请填写执行说明、核验证据及实际生效时间');if(!/T\d\d:\d\d(:\d\d)?(\+08:00|Z)$/.test(p.effectiveAt))error('生效时间需包含时区');{const d=shanghaiDay(p.effectiveAt);if(d>s.clock)error('实际生效时间不能晚于演示业务日');const pr=s.products.find(x=>x.id===t.productId);if(pr&&d<pr.listed)error('实际生效时间不能早于商品上架日期');if(p.outcome!=='already_exists'){const why=blocking(s,t);if(why)error(why);}}
  const sub={id:'SUB-'+t.id+'-'+((t.submissions||[]).length+1),by:actor,submittedAt:new Date().toISOString(),note:cleanText(p.note),evidence:cleanText(p.evidence),effectiveAt:p.effectiveAt,artifactVersion:p.artifactVersion,outcome:p.outcome||'performed',attachments:clone(p.attachments||[])};
  if(sub.attachments.length>3||JSON.stringify(sub.attachments).length>2100000)error('附件超过本地演示容量');
  t.submissions=t.submissions||[];t.submissions.push(sub);t.status='review';bump(t);enqueue(s,t,'待核验');detail='提交回执 '+sub.id+'，不自动核验通过';break;
 case 'verify':if(t.verifier!==actor&&!lead)error('没有核验权限');if(t.status!=='review')error('当前没有待核验提交');{const sub=t.submissions?.at(-1);if(!sub)error('缺少执行证据');if(sub.by===actor)error('本演示不允许本人核验自己的提交');if(!cleanText(p.note))error('请填写核验结论或退回原因');if(p.decision==='approve'&&sub.artifactVersion!==t.artifactVersion)error('产物版本已更新，旧提交不能核验通过');if(!['approve','reject'].includes(p.decision))error('核验结果无效');
  t.reviews=t.reviews||[];t.reviews.push({by:actor,at:new Date().toISOString(),decision:p.decision,note:cleanText(p.note),submissionId:sub.id,artifactVersion:sub.artifactVersion});
  if(p.decision==='approve'){t.status='done';t.effectiveAt=sub.effectiveAt;t.verifiedAt=new Date().toISOString();t.resolution='executed';if(sub.outcome==='already_exists'){t.plan={...t.plan,enabled:false,reason:'存量状态核查，不作为新动作评估'};}}else{t.status='running';delete t.effectiveAt;}
  bump(t);t.syncStatus='pending';enqueue(s,t,p.decision==='approve'?'核验通过':'退回修改');detail=p.decision==='approve'?'执行核验通过；经营效果单独观察':'退回修改：'+cleanText(p.note);}break;
 case 'reviseArtifact':if(t.owner!==actor&&!lead)error('没有修改产物权限');if(CLOSED.has(t.status))error('已完成任务需建立新的修改需求');if(!cleanText(p.content))error('新版说明不能为空');t.artifacts=t.artifacts||[];t.artifacts.push({version:t.artifactVersion,content:t.artifactContent||'原演示产物',archivedAt:new Date().toISOString()});t.artifactVersion+=1;t.artifactContent=cleanText(p.content);bump(t);detail='产物升至 v'+t.artifactVersion+'；旧核验不覆盖新版';break;
 case 'coordinate':if(!lead)error('仅演示主管可确认跨端口协调');if(!cleanText(p.reason))error('需要协调原因');if(conflicts(s,t).some(x=>x.level==='hard'))error('直接冲突不可一键放行，请调整排期或取消重复动作');t.coordination={by:actor,reason:cleanText(p.reason),signature:conflictSignature(conflicts(s,t)),at:new Date().toISOString()};bump(t);detail='确认组合观察：'+t.coordination.reason;break;
 case 'reschedule':if(!lead&&t.owner!==actor)error('没有调整排期权限');if(CLOSED.has(t.status)||t.status==='review')error('当前状态不能改排期');if(!validDate(p.start)||!validDate(p.end)||p.start>p.end||!cleanText(p.reason))error('填写正确排期和原因');t.plannedStart=p.start;t.plannedEnd=p.end;t.observationEnd=addDays(p.end,Math.max(...(t.plan?.milestones||[0])));delete t.coordination;bump(t);detail='排期调整至 '+p.start+' — '+p.end+'；'+p.reason;break;
 case 'waive':if(!managerial)error('没有确认无需执行的权限');if(CLOSED.has(t.status))error('已结束任务不重复结束');if(!cleanText(p.reason)||!validDate(p.reviewDate))error('请填写原因与复核日期');t.status='waived';t.resolution='not_required';t.exception={reason:cleanText(p.reason),by:actor,reviewDate:p.reviewDate};bump(t);t.syncStatus='pending';detail='无需执行（不计已执行）：'+p.reason;break;
 case 'plan':if(t.owner!==actor&&!managerial)error('无跟踪计划编辑权限');validatePlan(p);if(t.status==='done'&&!cleanText(p.reason))error('生效后重设计划需原因；历史报告不覆盖');t.plan={enabled:p.enabled,metric:p.metric||'cr',baselineDays:p.baselineDays||7,milestones:[...(p.milestones||[3,7])].sort((a,b)=>a-b),minUV:p.minUV||500,recipients:p.recipients||[t.owner,t.verifier],cadence:p.cadence||'节点报告',recipientChoice:p.recipientChoice||'both',version:(t.plan?.version||0)+1,reason:cleanText(p.reason),configuredAt:new Date().toISOString()};bump(t);detail='跟踪配置 v'+t.plan.version+'；仅本地示例，不创建外部定时任务';break;
 case 'policy':if(!managerial)error('没有调整商品策略权限');if(!s.products.some(x=>x.id===p.productId)||!['stop_purchase','normal'].includes(p.mode))error('策略对象或模式无效');if(!cleanText(p.reason))error('请填写策略原因');if(!validDate(p.reviewDate))error('需要有效复核日期');{const old=currentPolicy(s,p.productId);if(p.policyVersion!==undefined&&p.policyVersion!==(old?.version||0))error('策略版本冲突');if(old)old.active=false;const pol={id:'POL-'+p.productId+'-'+((old?.version||0)+1),productId:p.productId,mode:p.mode,version:(old?.version||0)+1,reason:cleanText(p.reason),reviewDate:p.reviewDate,by:actor,active:true,at:new Date().toISOString(),reverts:p.reverts||null};s.policies.push(pol);for(const task of s.tasks.filter(x=>x.productId===p.productId&&!CLOSED.has(x.status)&&x.kind==='purchase')){task.strategyReview=true;bump(task);}detail='商品 '+p.productId+' 策略 v'+pol.version+'；库存事实保持原值';}break;
 case 'create':{if(!cleanText(p.title,160))error('请输入任务标题');if(p.productId&&!s.products.some(x=>x.id===p.productId))error('商品不存在');const own=p.owner||actor;if(own!==actor&&!lead)error('专员只能创建自己的临时任务，主管可派给其他人');if(!s.users.some(x=>x.id===own)||!s.users.some(x=>x.id===(p.verifier||'lead')))error('人员不存在');if(!['日常','活动','专项'].includes(p.scenario))error('请选择业务场景');if(!validDate(p.due))error('截止日期无效');if(p.requestKey&&s.tasks.some(x=>x.requestKey===p.requestKey&&!CLOSED.has(x.status))){const exist=s.tasks.find(x=>x.requestKey===p.requestKey&&!CLOSED.has(x.status));s.lastCreated=exist.id;detail='复用未结束任务 '+exist.id;break;}
  const id='TASK-'+(s.tasks.length+1).toString().padStart(3,'0');t={id,title:cleanText(p.title,160),productId:p.productId||'',kind:p.kind||'manual',resource:p.resource||'manual',status:'queued',owner:own,verifier:p.verifier||'lead',version:1,artifactVersion:1,artifactContent:cleanText(p.requirement||p.title),source:p.source||'手工临时',scenario:p.scenario,activity:p.activity||'',requirement:cleanText(p.requirement),requestKey:p.requestKey||id,plannedStart:s.clock,plannedEnd:p.due,observationEnd:p.due,due:p.due,priority:'normal',sourceStage:'非阶段规则派生',syncStatus:'pending',plan:{enabled:false,metric:'cr',baselineDays:7,milestones:[3,7],minUV:500,version:1},submissions:[],reviews:[],artifacts:[]};s.tasks.unshift(t);s.lastCreated=id;enqueue(s,t,'新任务');detail='创建演示任务 '+id+'；未发到飞书';}break;
 case 'evaluateAll':{let count=0;for(const task of s.tasks){for(const m of task.plan?.enabled?task.plan.milestones:[]){const r=evaluate(s,task,m);if(!['ready','insufficient','waiting'].includes(r.status))continue;const key=JSON.stringify([task.id,task.plan.version,m,r.status,r.before,r.after,r.missing,r.confounds]);if(s.reports.some(x=>x.key===key))continue;r.key=key;r.id='R-'+(s.reports.length+1).toString().padStart(4,'0');r.createdAt=new Date().toISOString();s.reports.unshift(r);if(r.status==='ready'&&task.plan.cadence!=='仅工作台展示'){for(const who of new Set(task.plan.recipients||[task.owner,task.verifier])){enqueue(s,{...task,owner:who},'效果报告',r.id+'|'+who);}}count++;}}detail='本地生成 '+count+' 个新评估快照；缺数不补零，通知仅排队演示';}break;
 case 'sync':{for(const task of s.tasks.filter(t=>['pending','failed'].includes(t.syncStatus)))task.syncStatus=(s.flags.syncFail||!s.flags.macOnline)?'failed':'simulated';for(const n of s.notifications.filter(x=>['pending','failed'].includes(x.status)))n.status=s.flags.macOnline&&!s.flags.syncFail?'simulated':'failed';detail=(s.flags.syncFail||!s.flags.macOnline)?'模拟同步失败／执行端离线；反馈仍保留':'本地回写/通知演示完成，未访问飞书';}break;
 case 'macToggle':s.flags.macOnline=!s.flags.macOnline;detail='Mac执行端模拟 '+(s.flags.macOnline?'在线':'离线')+'；本机反馈操作不受此模拟开关影响';break;
 case 'syncFailToggle':s.flags.syncFail=!s.flags.syncFail;detail='模拟同步失败开关 '+s.flags.syncFail;break;
 case 'dataAdvance':if(!s.flags.macOnline)error('模拟执行端离线：数据更新暂停，反馈仍可保存');{const target=p.date||addDays(s.completeThrough,7);if(!validDate(target)||target>s.demoDataEnd||target<s.completeThrough)error('演示数据日期超出可用范围');s.completeThrough=target;s.clock=addDays(target,1);s.dataVersion++;detail='完整数据演示推进至 '+target+'；不会运行CLI或写源表';}break;
 case 'refresh':s.dataVersion++;for(const source of s.sources)if(source.status==='success')source.readAt=s.clock;detail='重读相同演示来源：不覆盖任务、回执和策略';break;
 default:error('不支持的操作');}
 s.requests[command.requestId]=fingerprint;addEvent(s,actor,command.type,t?.id||p.productId||'SYSTEM',detail);return s;
}
function refreshSnapshot(input,patch){const s=clone(input);if(!validDate(patch.completeThrough))error('完整销售日无效');if(patch.completeThrough<s.completeThrough)error('旧批次不可覆盖新日期');s.completeThrough=patch.completeThrough;s.dataVersion++;if(patch.sources)s.sources=clone(patch.sources);return s;}
function validateBackup(s){if(!s||s.schema!=='hm-pilot-v7'||s.version!==1||!validDate(s.clock)||!validDate(s.completeThrough))error('备份格式或版本无效');for(const k of ['users','products','tasks','daily','events','policies','notifications','reports','sources'])if(!Array.isArray(s[k]))error('备份格式缺少 '+k);if(!s.flags||typeof s.flags.macOnline!=='boolean'||typeof s.flags.syncFail!=='boolean'||!validDate(s.demoDataEnd)||s.completeThrough>s.demoDataEnd||!Number.isInteger(s.dataVersion)||s.dataVersion<1)error('备份运行配置格式无效');
 for(const u of s.users)if(!['operator','manager','merch'].includes(u.role)||typeof u.name!=='string')error('备份人员格式无效');
 for(const p of s.products)if(!validDate(p.listed)||typeof p.name!=='string'||typeof p.article!=='string'||typeof p.concept!=='string'||typeof p.category!=='string'||!finite(p.stock)||p.stock<0)error('备份商品或上架日期无效');
 for(const t of s.tasks)if(typeof t.title!=='string'||typeof t.productId!=='string'||!validDate(t.due)||!validDate(t.plannedStart)||!Number.isInteger(t.artifactVersion)||!Array.isArray(t.submissions)||!Array.isArray(t.artifacts)||!Array.isArray(t.reviews))error('备份任务格式无效');
 if(s.tasks.length>5000||s.daily.length>100000||JSON.stringify(s).length>4500000)error('备份超过演示容量');for(const k of ['users','products','tasks']){const ids=s[k].map(x=>x.id);if(ids.some(x=>typeof x!=='string'||!x)||new Set(ids).size!==ids.length)error('备份包含无效或重复ID');}for(const t of s.tasks){if(!['queued','running','review','done','blocked','waived','cancelled'].includes(t.status)||!Number.isInteger(t.version)||!s.users.some(x=>x.id===t.owner)||!s.users.some(x=>x.id===t.verifier)||t.productId&&!s.products.some(x=>x.id===t.productId))error('备份任务关联或状态无效');validatePlan(t.plan);}for(const r of s.daily)if(!s.products.some(x=>x.id===r.productId)||!validDate(r.date)||r.uv!==null&&(!finite(r.uv)||r.uv<0)||r.buyers!==null&&(!finite(r.buyers)||r.buyers<0))error('备份经营明细无效');return clone(s);}
return {clone,validDate,addDays,dayDiff,shanghaiDay,inNewList,isManager,currentPolicy,conflicts,conflictSignature,blocking,evaluate,aggregateWindow,datesBetween,applyCommand,refreshSnapshot,validateBackup,validatePlan,CLOSED};
});
