/* Dependency-free OOXML export for small, synthetic demo summaries. IDs are inline strings. */
(function(root,factory){const a=factory();if(typeof module==='object'&&module.exports)module.exports=a;else root.HMExport=a;})(typeof globalThis!=='undefined'?globalThis:this,function(){
 const enc=s=>new TextEncoder().encode(s);const xml=s=>String(s??'').replace(/[\x00-\x08\x0B\x0C\x0E-\x1F]/g,'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[c]));
 const crcTable=Array.from({length:256},(_,n)=>{for(let k=0;k<8;k++)n=n&1?0xedb88320^(n>>>1):n>>>1;return n>>>0;});
 function crc(a){let c=0xffffffff;for(const b of a)c=crcTable[(c^b)&255]^(c>>>8);return (c^0xffffffff)>>>0;}
 function u16(a,n){a.push(n&255,(n>>>8)&255);}function u32(a,n){a.push(n&255,(n>>>8)&255,(n>>>16)&255,(n>>>24)&255);}function concat(arr){const r=new Uint8Array(arr.reduce((n,a)=>n+a.length,0));let off=0;for(const a of arr){r.set(a,off);off+=a.length;}return r;}
 function zip(files){const pieces=[],dirs=[];let offset=0;for(const [name,text]of Object.entries(files)){const n=enc(name),d=enc(text),c=crc(d),h=[];u32(h,0x04034b50);u16(h,20);u16(h,0x800);u16(h,0);u16(h,0);u16(h,33);u32(h,c);u32(h,d.length);u32(h,d.length);u16(h,n.length);u16(h,0);const head=concat([new Uint8Array(h),n]);pieces.push(head,d);let z=[];u32(z,0x02014b50);u16(z,20);u16(z,20);u16(z,0x800);u16(z,0);u16(z,0);u16(z,33);u32(z,c);u32(z,d.length);u32(z,d.length);u16(z,n.length);u16(z,0);u16(z,0);u16(z,0);u16(z,0);u32(z,0);u32(z,offset);dirs.push(new Uint8Array(z),n);offset+=head.length+d.length;}const dir=concat(dirs),end=[];u32(end,0x06054b50);u16(end,0);u16(end,0);u16(end,Object.keys(files).length);u16(end,Object.keys(files).length);u32(end,dir.length);u32(end,offset);u16(end,0);return concat([...pieces,dir,new Uint8Array(end)]);}
 function col(n){let s='';for(n++;n;n=Math.floor((n-1)/26))s=String.fromCharCode(65+(n-1)%26)+s;return s;}
 function xlsx(rows,name='演示执行清单'){if(!Array.isArray(rows)||!rows.length)throw Error('导出数据为空');const ns='http://schemas.openxmlformats.org/spreadsheetml/2006/main',last=col(Math.max(...rows.map(r=>r.length))-1)+rows.length;
 const data=rows.map((r,i)=>`<row r="${i+1}" ht="${i===0?28:35}" customHeight="1">${r.map((v,j)=>{const ref=col(j)+(i+1);return typeof v==='number'&&Number.isFinite(v)?`<c r="${ref}" s="${i===0?1:2}"><v>${v}</v></c>`:`<c r="${ref}" s="${i===0?1:2}" t="inlineStr"><is><t xml:space="preserve">${xml(v)}</t></is></c>`;}).join('')}</row>`).join('');
 return zip({
 '[Content_Types].xml':`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/><Override PartName="/xl/worksheets/sheet1.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/><Override PartName="/xl/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.styles+xml"/></Types>`,
 '_rels/.rels':'<?xml version="1.0"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/></Relationships>',
 'xl/workbook.xml':`<?xml version="1.0" encoding="UTF-8"?><workbook xmlns="${ns}" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets><sheet name="${xml(name.slice(0,31))}" sheetId="1" r:id="rId1"/></sheets></workbook>`,
 'xl/_rels/workbook.xml.rels':'<?xml version="1.0"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet1.xml"/><Relationship Id="rId2" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/></Relationships>',
 'xl/styles.xml':`<?xml version="1.0"?><styleSheet xmlns="${ns}"><fonts count="2"><font><sz val="11"/><name val="Calibri"/></font><font><b/><sz val="11"/><color rgb="FFFFFFFF"/><name val="Calibri"/></font></fonts><fills count="3"><fill><patternFill patternType="none"/></fill><fill><patternFill patternType="gray125"/></fill><fill><patternFill patternType="solid"><fgColor rgb="FF152D3F"/><bgColor indexed="64"/></patternFill></fill></fills><borders count="1"><border><left/><right/><top/><bottom/><diagonal/></border></borders><cellStyleXfs count="1"><xf numFmtId="0" fontId="0" fillId="0" borderId="0"/></cellStyleXfs><cellXfs count="3"><xf numFmtId="0" fontId="0" fillId="0" borderId="0" xfId="0"/><xf numFmtId="0" fontId="1" fillId="2" borderId="0" xfId="0" applyAlignment="1"><alignment vertical="center" wrapText="1"/></xf><xf numFmtId="0" fontId="0" fillId="0" borderId="0" xfId="0" applyAlignment="1"><alignment vertical="center" wrapText="1"/></xf></cellXfs><cellStyles count="1"><cellStyle name="Normal" xfId="0" builtinId="0"/></cellStyles></styleSheet>`,
 'xl/worksheets/sheet1.xml':`<?xml version="1.0" encoding="UTF-8"?><worksheet xmlns="${ns}"><dimension ref="A1:${last}"/><sheetViews><sheetView workbookViewId="0"><pane xSplit="1" ySplit="1" topLeftCell="B2" activePane="bottomRight" state="frozen"/></sheetView></sheetViews><sheetFormatPr defaultRowHeight="20"/><cols>${rows[0].map((_,j)=>`<col min="${j+1}" max="${j+1}" width="${j===1||j===2?32:22}" customWidth="1"/>`).join('')}</cols><sheetData>${data}</sheetData><autoFilter ref="A1:${last}"/></worksheet>`});}
 return {xml,zip,xlsx};
});
