/* V9: local-only planning, recurrence, workload and daily-snapshot demo.
   All dates are Asia/Shanghai wall times. No network, timer or production authorization. */
(function(root,f){if(typeof module==='object'&&module.exports)module.exports=f(require('./core.js'),require('./analytics.js'));else root.HMV9=f(root.HMPilot,root.HMAnalytics);})(typeof globalThis!=='undefined'?globalThis:this,function(C,A){'use strict';
const clone=C.clone,CLOSED=C.CLOSED,HIGH=new Set(['price','ad_budget','purchase']);
const assert=(v,msg)=>{if(!v)throw Error(msg);};
const text=(v,n=2000)=>String(v??'').trim().slice(0,n);
const validTime=v=>typeof v==='string'&&/^\d{2}:\d{2}$/.test(v)&&v<'24:00'&&Number(v.slice(3))<60;
const validAt=v=>typeof v==='string'&&v.length===16&&C.validDate(v.slice(0,10))&&v[10]==='T'&&validTime(v.slice(11));
const dateOf=v=>String(v||'').slice(0,10);
const atNow=s=>s.clock+'T'+(s.workTime||'17:00');
const lead=(s,u)=>['manager','merch'].includes(s.users.find(x=>x.id===u)?.role);
const editable=(s,t,u)=>t.owner===u||t.creator===u||lead(s,u);
const userExists=(s,id)=>s.users.some(u=>u.id===id);
const related=(t,id)=>t.owner===id||(t.collaborators||[]).includes(id)||t.verifier===id;
const uid=(prefix,xs)=>prefix+'-'+String(Math.max(0,...xs.map(x=>Number(String(x.id).split('-').at(-1))||0))+1).padStart(4,'0');
function note(s,actor,type,id,detail,extra={}){s.events.unshift({id:uid('V9-EV',s.events),at:new Date().toISOString(),businessDate:s.clock,actor,action:type,objectId:id,detail,...extra});}
function notify(s,t,type){const people=[...new Set([t.owner,...(t.collaborators||[]),t.verifier,t.creator].filter(x=>userExists(s,x)))];for(const who of people)s.inbox.unshift({id:uid('IN',s.inbox),taskId:t.id,type,recipient:who,revision:t.version,createdAt:atNow(s),readAt:null,demo:true});}
function reminders(s,t){for(const r of s.reminders)if(r.taskId===t.id&&r.status==='pending')r.status='superseded';if(!CLOSED.has(t.status))s.reminders.push({id:uid('REM',s.reminders),taskId:t.id,at:t.dueAt,scheduleVersion:t.scheduleVersion,status:'pending',type:'到期提醒（模拟）'});}
function baseSchedule(t,s){t.startAt=t.startAt||t.plannedStart+'T09:00';t.dueAt=t.dueAt||t.due+'T18:00';if(t.startAt>t.dueAt)t.startAt=dateOf(t.dueAt)+'T09:00';t.plannedStart=dateOf(t.startAt);t.plannedEnd=dateOf(t.dueAt);t.due=dateOf(t.dueAt);t.originalStartAt=t.originalStartAt||t.startAt;t.originalDueAt=t.originalDueAt||t.dueAt;t.scheduleVersion=t.scheduleVersion||1;t.scheduleHistory=t.scheduleHistory||[];t.collaborators=t.collaborators||[];t.effort=t.effort||[];t.creator=t.creator||'lead';t.createdDay=t.createdDay||s.clock;t.verificationRequired=t.verificationRequired!==false;t.dependencies=t.dependencies||[];t.assignmentHistory=t.assignmentHistory||[];t.initialOwner=t.initialOwner||t.owner;t.scheduleReview=t.scheduleReview||false;return t;}
function enrich(input){const s=clone(input);s.edition='v9';s.v9Version=1;s.workTime='17:00';s.series=[];s.inbox=[];s.reminders=[];s.daySnapshots=[];s.skills=[
 {id:'SK-NEW-CHECK',name:'新品状态核查',description:'接收既有阶段输出，检查来源与执行证据；不重写T+规则',mode:'instruction',requiresReview:true},
 {id:'SK-MATERIAL',name:'主图与素材优化',description:'生成素材任务与输入检查，批准后再执行',mode:'instruction',requiresReview:true},
 {id:'SK-DIAGNOSE',name:'品类经营诊断',description:'品类差异—流量转化—商品证据；真实接口待接入',mode:'instruction',requiresReview:false},
 {id:'SK-REPORT',name:'经营摘要整理',description:'基于已核验摘要形成内部交付物',mode:'instruction',requiresReview:false}
 ];
 s.users.forEach(u=>u.capacityMinutes=360); // Planning assumption, not recorded hours or performance.
 s.tasks.forEach((t,i)=>{baseSchedule(t,s);t.estimatedMinutes=[45,120,40,60,30,60,25,35,90,45,180,30][i%12];t.creator='lead';t.createdDay=t.status==='done'?dateOf(t.effectiveAt):s.clock;t.skillId=i===0?'SK-NEW-CHECK':t.kind==='report'?'SK-REPORT':t.kind==='main_image'?'SK-MATERIAL':'';if(t.status==='done'){t.completedDay=dateOf(t.effectiveAt);t.completedOwner=t.owner;}if(t.submissions?.length){t.submittedDay=dateOf(t.submissions.at(-1).effectiveAt);t.submittedBy=t.submissions.at(-1).by;}if(i===1){t.collaborators=['ops'];t.effort=[{userId:'ops',minutes:25}];}if(i===9)t.dependencies=['TASK-002'];notify(s,t,t.status==='review'?'待你确认':'任务已登记');reminders(s,t);});
 s.series=[{id:'SER-001',title:'新品数据批次复核（循环示例）',owner:'ops',creator:'lead',collaborators:[],verifier:'',verificationRequired:false,kind:'data_check',scenario:'日常',skillId:'SK-DIAGNOSE',estimatedMinutes:25,frequency:'weekdays',interval:1,anchor:s.clock,endDate:'2026-10-08',weekdays:[1,2,3,4,5],monthDay:22,startTime:'10:30',dueTime:'11:30',dueOffset:0,active:true,version:1,requirement:'仅演示循环实例生成；不替代或重复创建现有automation-3。',history:[]}];
 s.shopDays=[];s.targetDays=[];
 for(const platform of ['天猫','京东']){const ids=new Set(s.products.filter(p=>p.platform===platform).map(p=>p.id));for(let d='2026-08-18';d<='2026-10-08';d=C.addDays(d,1)){const rows=s.daily.filter(x=>ids.has(x.productId)&&x.date===d);if(!rows.length)continue;const k=C.dayDiff('2026-08-18',d),gmv=rows.reduce((n,r)=>n+(r.gmv||0),0),rawUV=rows.reduce((n,r)=>n+(r.uv||0),0);const visitCount=Math.max(20,Math.round(rawUV*.67)),visitStart=(k*317)%6000,buyerCount=Math.max(1,Math.round(visitCount*.036));s.shopDays.push({date:d,platform,gmv,visitStart,visitCount,buyerStart:visitStart+Math.min(200,visitCount-buyerCount),buyerCount,ready:true,source:'独立店铺模拟快照（非商品UV简单相加）'});s.targetDays.push({date:d,platform,value:Math.round(gmv*(d>='2026-09-15'?1.12:1.04)/100)*100,planVersion:'DEMO-PLAN-01',approved:true});}}
 s.targetYear={'天猫':90000000,'京东':30000000};s.activity={id:'DEMO-AUTUMN',title:'秋季主题周（演示）',start:'2026-09-18',end:'2026-09-25'};
 s.sourceBindings={targetActual:{kind:'feishu_bitable',wikiNode:'CAHuw79iuisU4KkkR70c92qIn9g',tableId:'tblmADtYmyYFAkT3',status:'未联调'},newProducts:{kind:'feishu_sheets',documentId:'MyCbs1EN6hbtBTtJaQHc6bzunHc',status:'未联调'},taskLedger:{kind:'feishu_bitable',status:'任务台账待建'},biMcp:{status:'安装与字段能力待核验'},xuanji:{status:'运行接口与共享服务待核验'}};
 return s;
}
function schedulePreview(s,id,p){const t=s.tasks.find(t=>t.id===id);assert(t,'任务不存在');const startAt=p.startAt||p.start+'T'+t.startAt.slice(11),dueAt=p.dueAt||p.end+'T'+t.dueAt.slice(11);assert(validAt(startAt)&&validAt(dueAt)&&startAt<=dueAt,'开始时间不得晚于截止时间，且需要有效日期');const projected=clone(s),n=projected.tasks.find(x=>x.id===id);Object.assign(n,{startAt,dueAt,plannedStart:dateOf(startAt),plannedEnd:dateOf(dueAt),due:dateOf(dueAt),observationEnd:C.addDays(dateOf(dueAt),Math.max(...(n.plan?.enabled?n.plan.milestones:[0])))});const dependencies=[];
 for(const t2 of projected.tasks){if((t2.dependencies||[]).includes(id)&&!CLOSED.has(t2.status)&&t2.startAt<dueAt)dependencies.push({id:t2.id,title:t2.title,detail:'下游计划开始早于新的上游截止'});if((n.dependencies||[]).includes(t2.id)&&!CLOSED.has(t2.status)&&t2.dueAt>startAt)dependencies.push({id:t2.id,title:t2.title,detail:'本任务计划早于上游预计完成'});}
 return {before:{startAt:t.startAt,dueAt:t.dueAt},after:{startAt,dueAt},conflicts:C.conflicts(projected,n),dependencies,recipients:[...new Set([t.owner,...(t.collaborators||[]),t.verifier,t.creator].filter(Boolean))]};
}
function allocateDays(t){const all=C.datesBetween(dateOf(t.startAt),dateOf(t.dueAt));const work=all.filter(d=>{let day=new Date(d+'T00:00:00Z').getUTCDay();return day>0&&day<6;});return work.length?work:all;}
function allocatedMinutes(t,userId,date){const days=allocateDays(t);if(!days.includes(date))return 0;const n=t.owner===userId?t.estimatedMinutes:(t.effort||[]).find(x=>x.userId===userId)?.minutes;return Number.isFinite(n)?n/days.length:0;}
function calendar(s,start,end,{actor='',all=true,ended=false}={}){assert(C.validDate(start)&&C.validDate(end)&&start<=end,'日历日期无效');return s.tasks.filter(t=>(all||related(t,actor))&&(ended||!CLOSED.has(t.status))&&dateOf(t.startAt)<=end&&dateOf(t.dueAt)>=start).sort((a,b)=>a.startAt.localeCompare(b.startAt)||a.id.localeCompare(b.id));}
function isOverdue(s,t){return !CLOSED.has(t.status)&&t.dueAt<atNow(s);}
function visibleTasks(s,{actor='',relation='involved',all=false,ended=false,date='',search=''}={}){return s.tasks.filter(t=>(all||relation==='created'?all||t.creator===actor:relation==='owned'?t.owner===actor:relation==='verify'?t.verifier===actor&&t.status==='review':related(t,actor))&&(ended?CLOSED.has(t.status):!CLOSED.has(t.status))&&(!date||(dateOf(t.startAt)<=date&&dateOf(t.dueAt)>=date)||!ended&&date&&date>=s.clock&&t.due<date)&&(!search||[t.id,t.title,t.productId].join(' ').toLowerCase().includes(search.toLowerCase()))).sort((a,b)=>{const rank=t=>(t.status==='review'&&t.verifier===actor?0:isOverdue(s,t)?1:t.priority==='high'?2:3)+(t.startAt>atNow(s)?5:0);return rank(a)-rank(b)||a.dueAt.localeCompare(b.dueAt);});}
function workload(s,date){assert(C.validDate(date),'负荷日期无效');return s.users.map(u=>{const scheduled=s.tasks.filter(t=>related(t,u.id)&&!['cancelled','waived'].includes(t.status)&&dateOf(t.startAt)<=date&&t.due>=date),work=scheduled.filter(t=>t.owner===u.id||(t.collaborators||[]).includes(u.id));const open=s.tasks.filter(t=>t.owner===u.id&&!CLOSED.has(t.status)&&dateOf(t.startAt)<=date&&((t.due>=date)||(date>=s.clock&&t.due<date)));const involved=s.tasks.filter(t=>t.owner===u.id&&!['cancelled','waived'].includes(t.status));return {id:u.id,name:u.name,planned:work.length,owned:work.filter(t=>t.owner===u.id).length,collaborating:work.filter(t=>t.owner!==u.id).length,taskIds:work.map(t=>t.id),minutes:work.reduce((n,t)=>n+allocatedMinutes(t,u.id,date),0),capacity:u.capacityMinutes||360,unknown:work.filter(t=>!Number.isFinite(t.owner===u.id?t.estimatedMinutes:t.effort?.find(x=>x.userId===u.id)?.minutes)).length,added:s.tasks.filter(t=>(t.initialOwner===u.id&&t.createdDay===date)||(t.assignmentHistory||[]).some(h=>h.to===u.id&&h.date===date)).length,submitted:s.tasks.filter(t=>t.submittedDay===date&&(t.submittedBy||t.submissions?.at(-1)?.by||t.owner)===u.id).length,completed:s.tasks.filter(t=>t.completedDay===date&&(t.completedOwner||t.owner)===u.id).length,waiting:open.filter(t=>t.status==='review').length,blocked:open.filter(t=>t.status==='blocked'||blocking(s,t)).length,remaining:open.filter(t=>t.status!=='review').length,overdue:open.filter(t=>t.status!=='review'&&(date<s.clock?t.due<date:t.dueAt<date+'T'+(s.workTime||'17:00'))).length,reviewing:s.tasks.filter(t=>t.verifier===u.id&&t.status==='review').length};});}
function occurrences(r,from,to){assert(C.validDate(from)&&C.validDate(to)&&from<=to&&C.dayDiff(from,to)<=366,'循环生成范围最多367天');assert(C.validDate(r.anchor),'循环锚点无效');let out=[];for(let d=from;d<=to;d=C.addDays(d,1)){if(d<r.anchor||r.endDate&&d>r.endDate)continue;const dow=new Date(d+'T00:00:00Z').getUTCDay(),diff=C.dayDiff(r.anchor,d),interval=r.interval||1;let hit=false;if(r.frequency==='daily')hit=diff%interval===0;else if(r.frequency==='weekdays')hit=dow>=1&&dow<=5;else if(r.frequency==='weekly')hit=(r.weekdays||[]).includes(dow)&&Math.floor(diff/7)%interval===0;else if(r.frequency==='monthly'){let a=new Date(r.anchor+'T00:00:00Z'),b=new Date(d+'T00:00:00Z');let months=(b.getUTCFullYear()-a.getUTCFullYear())*12+b.getUTCMonth()-a.getUTCMonth();hit=b.getUTCDate()===r.monthDay&&months%interval===0;}if(hit)out.push(d);}return out;}
function validateSeries(r){assert(['daily','weekdays','weekly','monthly'].includes(r.frequency),'请选择有效循环方式');assert(C.validDate(r.anchor)&&(!r.endDate||C.validDate(r.endDate)&&r.endDate>=r.anchor),'循环结束日期无效');assert(validTime(r.startTime)&&validTime(r.dueTime),'循环时间无效');assert(Number.isInteger(r.interval)&&r.interval>=1&&r.interval<=52,'循环间隔应为1–52');assert(Number.isInteger(r.dueOffset)&&r.dueOffset>=0&&r.dueOffset<=30,'循环交付偏移无效');assert(r.dueOffset||r.startTime<=r.dueTime,'同日截止不得早于开始');if(r.frequency==='weekly')assert(Array.isArray(r.weekdays)&&r.weekdays.length&&r.weekdays.every(d=>Number.isInteger(d)&&d>=0&&d<=6),'每周任务需选择星期');if(r.frequency==='monthly')assert(Number.isInteger(r.monthDay)&&r.monthDay>=1&&r.monthDay<=31,'每月日期无效');}
function createTask(s,p,actor){const owner=p.owner||actor,collaborators=[...new Set((Array.isArray(p.collaborators)?p.collaborators:[]).filter(id=>id!==owner))];assert(text(p.title,160),'请输入任务标题');assert(userExists(s,owner)&&collaborators.every(u=>userExists(s,u)),'负责人或协作者不存在');assert(!p.productId||s.products.some(x=>x.id===p.productId),'商品不存在');assert(['日常','活动','专项'].includes(p.scenario||'日常'),'场景无效');assert(!p.skillId||s.skills.some(x=>x.id===p.skillId),'Skill尚未登记');const kind=p.kind||'manual',required=p.verificationRequired===true||p.verificationRequired==='true';const sk=s.skills.find(x=>x.id===p.skillId);assert(!HIGH.has(kind)||required,'此受控动作必须设置独立核验人');assert(!sk?.requiresReview||required,'所选Skill要求核验');const verifier=required?p.verifier:'';assert(!required||userExists(s,verifier)&&verifier!==owner,'请指定不同于负责人的核验人');const startAt=p.startAt||s.clock+'T09:00',dueAt=p.dueAt||(p.due||s.clock)+'T18:00';assert(validAt(startAt)&&validAt(dueAt)&&startAt<=dueAt&&C.dayDiff(dateOf(startAt),dateOf(dueAt))<=180,'开始与截止时间无效或跨度超过180天');const estimate=p.estimatedMinutes===''||p.estimatedMinutes==null?null:Number(p.estimatedMinutes);assert(estimate===null||Number.isFinite(estimate)&&estimate>=0&&estimate<=10000,'预计人工分钟数无效');const cm=p.collaboratorMinutes===''||p.collaboratorMinutes==null?null:Number(p.collaboratorMinutes);assert(cm===null||Number.isFinite(cm)&&cm>=0&&cm<=10000,'协作投入无效');const id=uid('TASK',s.tasks),key=p.requestKey||id;const existing=s.tasks.find(t=>t.requestKey===key&&(!CLOSED.has(t.status)||p.seriesId));if(existing){s.lastCreated=existing.id;return existing;}
 const t={id,title:text(p.title,160),productId:p.productId||'',kind,resource:p.resource||(kind==='main_image'?'main_image:1':kind==='video'?'video:main':kind),status:'queued',owner,collaborators,effort:collaborators.map(userId=>({userId,minutes:cm})),verifier,verificationRequired:required,creator:actor,createdDay:s.clock,estimatedMinutes:estimate,version:1,artifactVersion:1,artifactContent:text(p.requirement)||'本任务尚无AI产物；请按要求执行。',source:p.source||'工作台新建（演示）',scenario:p.scenario||'日常',activity:p.activity||'',requirement:text(p.requirement),requestKey:key,startAt,dueAt,plannedStart:dateOf(startAt),plannedEnd:dateOf(dueAt),due:dateOf(dueAt),observationEnd:dateOf(dueAt),priority:p.priority==='high'?'high':'normal',sourceStage:p.sourceStage||'非原T+阶段算法',syncStatus:'pending',submissions:[],reviews:[],artifacts:[],plan:{enabled:false,metric:'cr',baselineDays:7,milestones:[3,7],minUV:500,version:1},skillId:p.skillId||'',skill:sk?.name||'',dependencies:p.dependencies||[],seriesId:p.seriesId||'',occurrenceDate:p.occurrenceDate||'',seriesVersion:p.seriesVersion||null};baseSchedule(t,s);s.tasks.unshift(t);s.lastCreated=id;reminders(s,t);notify(s,t,'新任务');return t;
}
function blocking(s,t){if(!t)return '';const dep=(t.dependencies||[]).map(id=>s.tasks.find(x=>x.id===id)).find(x=>x&&!['done','waived'].includes(x.status));return dep?'等待上游任务 '+dep.id+' 完成':C.blocking(s,t);}
function apply(input,actor,command){assert(command?.requestId,'缺少请求标识');const fingerprint=JSON.stringify({actor,...command});const found=input.requests?.[command.requestId];if(found){assert(found===fingerprint,'重复请求的内容不同');return clone(input);}assert(userExists(input,actor),'无效演示身份');const s=clone(input),p=command.payload||{},type=command.type;let t=s.tasks.find(x=>x.id===command.id);const locals=new Set(['schedule','reschedule','create','generateSeries','editSeries','toggleSeries','snapshot','readInbox','reassign','cancel','startSkill']);
 if(locals.has(type)){
  if(['schedule','reschedule','reassign','cancel','startSkill'].includes(type)){assert(t,'任务不存在');assert(command.version===t.version,'记录版本已改变，请重新打开','CONFLICT');assert(editable(s,t,actor),'没有修改该任务的权限');assert(!CLOSED.has(t.status),'已结束任务不能改写；请建立新一轮工作');}
  let detail='';
  if(type==='schedule'||type==='reschedule'){
   assert(text(p.reason),'请填写改期原因');const preview=schedulePreview(s,t.id,p);assert(C.dayDiff(dateOf(preview.after.startAt),dateOf(preview.after.dueAt))<=180,'排期跨度超过180天');if(t.status==='review')assert(preview.after.startAt===t.startAt,'待确认任务仅允许调整截止时间，原开始与实际执行记录保留');
   const old={startAt:t.startAt,dueAt:t.dueAt,version:t.scheduleVersion},next=preview.after;t.startAt=next.startAt;t.dueAt=next.dueAt;t.plannedStart=dateOf(t.startAt);t.plannedEnd=dateOf(t.dueAt);t.due=dateOf(t.dueAt);t.observationEnd=C.addDays(t.due,Math.max(...(t.plan?.enabled?t.plan.milestones:[0])));t.scheduleVersion++;t.version++;t.scheduleHistory.push({before:old,after:{...next,version:t.scheduleVersion},by:actor,at:atNow(s),reason:text(p.reason),scope:'single_instance',actualTimesUnchanged:true});delete t.coordination;t.scheduleReview=preview.dependencies.length>0;t.manualScheduleOverride=!!t.seriesId;t.syncStatus='pending';for(const q of s.tasks)q.scheduleReview=false;for(const q of s.tasks.filter(x=>!CLOSED.has(x.status)))for(const id of q.dependencies||[]){const up=s.tasks.find(x=>x.id===id);if(up&&!CLOSED.has(up.status)&&up.dueAt>q.startAt){q.scheduleReview=true;up.scheduleReview=true;}}reminders(s,t);notify(s,t,'排期变更');detail=`排期 ${old.startAt} / ${old.dueAt} → ${t.startAt} / ${t.dueAt}；${p.reason}。日历/负荷按新版更新，实际生效与日终快照未改。`;
  }else if(type==='create'){
   t=createTask(s,p,actor);if(p.repeat&&p.repeat!=='none'&&!t.seriesId){const r={id:uid('SER',s.series),title:t.title,owner:t.owner,creator:actor,collaborators:t.collaborators,verifier:t.verifier,verificationRequired:t.verificationRequired,kind:t.kind,scenario:t.scenario,productId:t.productId,resource:t.resource,skillId:t.skillId,estimatedMinutes:t.estimatedMinutes,collaboratorMinutes:p.collaboratorMinutes===''||p.collaboratorMinutes==null?null:Number(p.collaboratorMinutes),frequency:p.repeat,interval:1,anchor:dateOf(t.startAt),endDate:p.repeatEnd||C.addDays(dateOf(t.startAt),60),weekdays:[new Date(dateOf(t.startAt)+'T00:00:00Z').getUTCDay()],monthDay:Number(t.startAt.slice(8,10)),startTime:t.startAt.slice(11),dueTime:t.dueAt.slice(11),dueOffset:C.dayDiff(dateOf(t.startAt),dateOf(t.dueAt)),active:true,version:1,requirement:t.requirement,history:[]};validateSeries(r);s.series.push(r);t.seriesId=r.id;t.occurrenceDate=r.anchor;t.seriesVersion=1;t.requestKey=r.id+'|'+r.anchor;}detail='创建或复用本机任务 '+t.id+'；未写入飞书或真实派发';
  }else if(type==='generateSeries'){
   const through=p.through||C.addDays(s.clock,7);assert(C.validDate(through)&&through>=s.clock&&C.dayDiff(s.clock,through)<=31,'一次最多生成未来31天');let count=0;for(const r of s.series.filter(x=>x.active)){validateSeries(r);for(const d of occurrences(r,s.clock,through)){if(s.tasks.some(t=>t.seriesId===r.id&&t.occurrenceDate===d))continue;const q=createTask(s,{...r,seriesId:r.id,seriesVersion:r.version,occurrenceDate:d,requestKey:r.id+'|'+d,source:'循环规则 '+r.id+'（模拟触发）',startAt:d+'T'+r.startTime,dueAt:C.addDays(d,r.dueOffset)+'T'+r.dueTime},r.creator||actor);count++;}}detail='模拟生成 '+count+' 次循环工作；发生日稳定去重；未创建真实定时任务';
  }else if(type==='editSeries'||type==='toggleSeries'){
   let r=s.series.find(x=>x.id===p.seriesId);assert(r,'循环规则不存在');assert(lead(s,actor)||r.creator===actor,'没有维护循环规则的权限');assert(p.seriesVersion===r.version,'循环规则版本冲突');assert(text(p.reason),'请填写规则修改原因');let old=clone(r);if(type==='toggleSeries')r.active=!r.active;else{r.startTime=p.startTime;r.dueTime=p.dueTime;if(p.endDate!==undefined)r.endDate=p.endDate;validateSeries(r);}r.version++;r.history.push({version:old.version,startTime:old.startTime,dueTime:old.dueTime,active:old.active,by:actor,at:atNow(s),reason:text(p.reason)});detail='循环规则 '+r.id+' v'+r.version+'；仅影响尚未生成的未来实例，已生成任务需逐条改期';
  }else if(type==='snapshot'){
   assert(lead(s,actor),'日终快照需要管理者身份');const date=p.date||s.clock,cutoff=p.cutoff||'18:00';assert(C.validDate(date)&&date===s.clock&&validTime(cutoff),'Demo只支持当前演示业务日快照；不回算历史状态');const key=date+'|'+cutoff;if(!s.daySnapshots.some(x=>x.key===key))s.daySnapshots.unshift({id:uid('EOD',s.daySnapshots),key,date,cutoff,simulated:true,capturedAt:atNow(s),capturedBy:actor,rows:workload({...s,workTime:cutoff},date),tasks:s.tasks.map(t=>({id:t.id,title:t.title,status:t.status,owner:t.owner,collaborators:t.collaborators,startAt:t.startAt,dueAt:t.dueAt,originalDueAt:t.originalDueAt,scheduleVersion:t.scheduleVersion,estimatedMinutes:t.estimatedMinutes,blockedReason:t.blockedReason||'',submittedDay:t.submittedDay,completedDay:t.completedDay}))});detail='模拟保存 '+date+' '+cutoff+' 日终快照；同键不覆盖；不是实际下班数据或后台调度';
  }else if(type==='readInbox'){for(const n of s.inbox)if(n.recipient===actor&&(p.ids||[]).includes(n.id))n.readAt=atNow(s);detail='标记本人通知已读，不改变执行状态';
  }else if(type==='reassign'){
   assert(lead(s,actor)||t.creator===actor,'仅发起人或管理者可重新分派');assert(userExists(s,p.owner),'主负责人不存在');assert(text(p.reason),'请填写分派原因');const collaborators=[...new Set((p.collaborators||[]).filter(x=>x!==p.owner))];assert(collaborators.every(x=>userExists(s,x)),'协作者不存在');assert(!t.verificationRequired||t.verifier!==p.owner,'新负责人不能兼任本任务核验人');const oldOwner=t.owner;t.assignmentHistory.push({from:oldOwner,to:p.owner,date:s.clock,at:atNow(s),by:actor,reason:text(p.reason)});t.owner=p.owner;t.collaborators=collaborators;t.effort=collaborators.map(userId=>({userId,minutes:(t.effort||[]).find(x=>x.userId===userId)?.minutes??null}));t.version++;t.syncStatus='pending';notify(s,{...t,collaborators:[...t.collaborators,oldOwner]},'负责人/协作变更');detail=`负责人 ${oldOwner} → ${t.owner}；${p.reason}，任务未复制`;
  }else if(type==='cancel'){assert(text(p.reason),'请填写取消原因');t.status='cancelled';t.resolution='cancelled';t.cancelReason=text(p.reason);t.version++;t.syncStatus='pending';reminders(s,t);notify(s,t,'任务取消');detail='取消，不计为执行完成：'+p.reason;
  }else if(type==='startSkill'){assert(t.skillId,'此任务未选择Skill');assert(!blocking(s,t),blocking(s,t));assert(t.startAt<=atNow(s),'尚未到计划开始时间');t.skillRun={id:uid('DEMO-RUN',s.tasks.map(x=>x.skillRun).filter(Boolean)),state:'not_connected',requestedAt:atNow(s),skillId:t.skillId};t.version++;detail='打开已登记Skill执行说明；真实执行器未接入，未改变为AI运行成功';}
  s.requests[command.requestId]=fingerprint;note(s,actor,type,t?.id||p.seriesId||'SYSTEM',detail);return s;
 }
 if(type==='start'){assert(t,'任务不存在');assert(t.startAt<=atNow(s),'尚未到计划开始时间，可先按权限调整排期');assert(!blocking(s,t),blocking(s,t));}
 if(type==='submit'&&t?.verificationRequired===false){assert(t.owner===actor,'仅主负责人可提交');assert(command.version===t.version,'记录版本已变化');assert(['queued','running','blocked'].includes(t.status),'当前状态不能重复提交');assert(!HIGH.has(t.kind),'受控任务不能免核验');assert(p.artifactVersion===t.artifactVersion,'产物版本已变化');assert(text(p.note),'请填写最低必要的交付结果');assert(!blocking(s,t),blocking(s,t));assert(t.startAt<=atNow(s),'尚未到计划开始时间；已提前执行请先按权限调整计划并保留原因');t.submissions.push({id:'SUB-'+t.id+'-'+(t.submissions.length+1),by:actor,submittedAt:atNow(s)+'+08:00',note:text(p.note),evidence:text(p.evidence),artifactVersion:t.artifactVersion,outcome:'delivered',attachments:clone(p.attachments||[])});assert(JSON.stringify(t.submissions.at(-1)).length<=2100000,'附件超过容量');t.status='done';t.completionMode='owner';t.resolution='delivered';t.submittedDay=s.clock;t.submittedBy=actor;t.completedDay=s.clock;t.completedOwner=t.owner;t.plan.enabled=false;t.version++;t.syncStatus='pending';reminders(s,t);notify(s,t,'任务完成');s.requests[command.requestId]=fingerprint;note(s,actor,type,t.id,'按免独立核验的交付要求完成；没有伪造核验或线上生效时间');return s;}
 let out=C.applyCommand(s,actor,command);const updated=out.tasks.find(x=>x.id===command.id);if(type==='submit'&&updated){updated.submittedDay=out.clock;updated.submittedBy=actor;notify(out,updated,'待确认');}if(type==='verify'&&updated&&p.decision==='approve'){updated.completedDay=out.clock;updated.completedOwner=updated.owner;reminders(out,updated);notify(out,updated,'核验通过');}if(type==='start'&&updated&&!updated.actualStartedAt)updated.actualStartedAt=atNow(out);if(type==='verify'&&p.decision==='reject'&&updated)notify(out,updated,'退回修改');return out;
}
function unionLength(ranges){if(!ranges.length)return 0;const a=ranges.map(x=>[x[0],x[0]+x[1]]).sort((x,y)=>x[0]-y[0]);let [start,end]=a[0],n=0;for(const [s,e]of a.slice(1)){if(s<=end)end=Math.max(end,e);else{n+=end-start;start=s;end=e;}}return n+end-start;}
function shopSummary(s,platform,start,end){assert(C.validDate(start)&&C.validDate(end)&&start<=end&&C.dayDiff(start,end)<=366,'查询区间无效或超过367天');const rows=s.shopDays.filter(x=>x.platform===platform&&x.date>=start&&x.date<=end&&x.date<=s.completeThrough&&x.ready);const needed=C.dayDiff(start,end)+1;let missing=[];for(let d=start;d<=end;d=C.addDays(d,1))if(!rows.some(x=>x.date===d))missing.push(d);if(missing.length)return {status:rows.length?'partial':'missing',gmv:null,partialGMV:rows.reduce((n,r)=>n+r.gmv,0),uv:null,cr:null,aov:null,missing,availableDays:rows.length,needed};const gmv=rows.reduce((n,r)=>n+r.gmv,0),uv=unionLength(rows.map(r=>[r.visitStart,r.visitCount])),buyers=unionLength(rows.map(r=>[r.buyerStart,r.buyerCount]));return {status:'ready',gmv,uv,buyers,cr:uv?buyers/uv:null,aov:buyers?gmv/buyers:null,missing:[],availableDays:needed,needed,dedupe:'独立店铺模拟访客区间去重；仅演示口径'};}
function period(s,kind,from,to){const d=s.completeThrough,year=d.slice(0,4),month=d.slice(0,7);if(kind==='today')return {start:s.clock,end:s.clock,fullStart:s.clock,fullEnd:s.clock,label:'今日'};if(kind==='yesterday')return {start:d,end:d,fullStart:d,fullEnd:d,label:'最近完整日'};if(kind==='activity')return {start:s.activity.start,end:d<s.activity.end?d:s.activity.end,fullStart:s.activity.start,fullEnd:s.activity.end,label:'活动累计'};if(kind==='mtd'){let e=new Date(Number(year),Number(d.slice(5,7)),0);return {start:month+'-01',end:d,fullStart:month+'-01',fullEnd:month+'-'+String(e.getDate()).padStart(2,'0'),label:'MTD 本月累计'};}if(kind==='ytd')return {start:year+'-01-01',end:d,fullStart:year+'-01-01',fullEnd:year+'-12-31',label:'YTD 本年累计'};return {start:from||C.addDays(d,-6),end:to||d,fullStart:from||C.addDays(d,-6),fullEnd:to||d,label:'自选周期'};}
function targetProgress(s,platform,kind,from,to){const p=period(s,kind,from,to),actual=shopSummary(s,platform,p.start,p.end);const totalRows=s.targetDays.filter(x=>x.platform===platform&&x.approved&&x.date>=p.fullStart&&x.date<=p.fullEnd),paceRows=totalRows.filter(x=>x.date<=p.end);const fullTarget=kind==='ytd'?s.targetYear[platform]:totalRows.length===C.dayDiff(p.fullStart,p.fullEnd)+1?totalRows.reduce((n,r)=>n+r.value,0):null;const pacedTarget=paceRows.length===C.dayDiff(p.start,p.end)+1?paceRows.reduce((n,r)=>n+r.value,0):null;return {...p,status:actual.status!=='ready'?actual.status:fullTarget===null||pacedTarget===null?'target_missing':'ready',actual:actual.gmv,fullTarget,pacedTarget,periodRate:actual.gmv!==null&&fullTarget>0?actual.gmv/fullTarget:null,paceRate:actual.gmv!==null&&pacedTarget>0?actual.gmv/pacedTarget:null,gap:actual.gmv!==null&&pacedTarget!==null?actual.gmv-pacedTarget:null,source:'模拟批准计划；真实多维表字段待映射',version:'DEMO-PLAN-01'};}
function validate(s){assert(s?.edition==='v9'&&s.v9Version===1,'仅支持V9存档，不覆盖或自动迁移旧版本');assert(Array.isArray(s.series)&&Array.isArray(s.inbox)&&Array.isArray(s.daySnapshots)&&Array.isArray(s.shopDays)&&Array.isArray(s.targetDays),'V9记录缺失');const copy=clone(s);copy.edition='v8';for(const t of copy.tasks){assert(validAt(t.startAt)&&validAt(t.dueAt)&&t.startAt<=t.dueAt&&dateOf(t.startAt)===t.plannedStart&&dateOf(t.dueAt)===t.due&&dateOf(t.dueAt)===t.plannedEnd,'任务日期关联无效');assert(t.verificationRequired===true||t.verificationRequired===false,'核验方式无效');assert(!t.verificationRequired||t.verifier!==t.owner,'负责人不可兼任核验人');assert(Array.isArray(t.collaborators)&&t.collaborators.every(id=>userExists(s,id))&&Array.isArray(t.scheduleHistory),'任务协作/历史无效');if(!t.verificationRequired)t.verifier='lead';}A.validate(copy);s.series.forEach(validateSeries);assert(JSON.stringify(s).length<=8000000,'存档超过演示容量');return clone(s);}
function bridge(core){return {...core,applyCommand:apply,validateBackup:validate,blocking};}
return {enrich,bridge,apply,validate,validAt,validTime,dateOf,atNow,related,isOverdue,visibleTasks,calendar,allocatedMinutes,workload,occurrences,schedulePreview,shopSummary,targetProgress,period,unionLength,blocking};
});
